$ErrorActionPreference = "Stop"

$manuscriptDir = $PSScriptRoot
$outputPath = Join-Path $manuscriptDir "FULL_MANUSCRIPT_DRAFT.md"
$sectionFiles = @(
    "ABSTRACT.md",
    "INTRODUCTION.md",
    "RELATED_WORK.md",
    "METHOD_AND_EXPERIMENTAL_SETUP.md",
    "RESULTS.md",
    "DISCUSSION_AND_LIMITATIONS.md",
    "CONCLUSION.md",
    "AVAILABILITY.md",
    "REFERENCES.md"
)

$parts = @(
    "<!-- Generated by manuscript/build_full_manuscript.ps1. Edit source sections, not this file. -->",
    "# Balancing Relevance and Overchallenge in Graph-Based Educational Recommendation: An Asymmetric Difficulty-Regularized LightGCN",
    "",
    "> **Drafting note:** author names, affiliations, corresponding-author details, and acknowledgments remain to be supplied."
)

foreach ($sectionFile in $sectionFiles) {
    $sectionPath = Join-Path $manuscriptDir $sectionFile
    if (-not (Test-Path -LiteralPath $sectionPath -PathType Leaf)) {
        throw "Missing manuscript section: $sectionPath"
    }
    $parts += ""
    $parts += (Get-Content -LiteralPath $sectionPath -Raw -Encoding UTF8).Trim()
}

$text = ($parts -join [Environment]::NewLine) + [Environment]::NewLine
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $text, $utf8NoBom)

Write-Output $outputPath
